### PR TITLE
Task 2 (Serve SPA in AWS S3 and Cloudfront Services)

### PR DESCRIPTION
**Pull request by v0f**
Task: https://github.com/EPAM-JS-Competency-center/cloud-development-course-initial/blob/main/task2-serve-spa-in-s3-cloudfront/task.md
Score: 5

#### manual deploy
s3 bucket: http://v0f-shop.s3-website.eu-central-1.amazonaws.com/
cloudfront: https://d228w013hobsso.cloudfront.net/
#### automated deploy
s3 bucket: http://v0f-shop-cfn.s3-website.eu-central-1.amazonaws.com/
cloudfront: https://d1a8te1scmlicl.cloudfront.net/

### CODE REVIEW

**Comment by kmisha** [comment]
Hi.

I don't see any links here. Can you please add links to s3/cloudfront resources?

**Comment by abulynka** [comment]
Hi.
The same problem.

**Comment by v0f** [comment]
@kmisha @abulynka Hi! Sorry, updated PR description with links

**Comment by kmisha** [comment]
Looks good for me. Many thanks!

**Pull request merged**
